services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: invest-portal-backend
    container_name: backend
    networks:
      - invest-net
    environment:
      ALPHA_VANTAGE_API_KEY: "${ALPHA_VANTAGE_API_KEY:-}"
      BRAPI_TOKEN: "${BRAPI_TOKEN:-}"
      COINGECKO_API_KEY: "${COINGECKO_API_KEY:-}"
      TWELVE_DATA_API_KEY: "${TWELVE_DATA_API_KEY:-}"
      MARKET_DATA_LOG_SOURCES: "1"
      MARKET_DATA_PROVIDERS: "${MARKET_DATA_PROVIDERS:-twelve_data,alpha_vantage,brapi,coingecko,google,yahoo}"
      MARKET_DATA_PROVIDERS_US: "${MARKET_DATA_PROVIDERS_US:-}"
      MARKET_DATA_PROVIDERS_CRYPTO: "${MARKET_DATA_PROVIDERS_CRYPTO:-}"
      MARKET_DATA_PROVIDERS_BR: "${MARKET_DATA_PROVIDERS_BR:-}"
    ports:
      - "8000:8000"
    volumes:
      - /srv/tyi-take_yout_investiments/investments.db:/app/investments.db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: invest-portal-frontend
    container_name: frontend
    networks:
      - invest-net
    environment:
      BASIC_AUTH_USER: "amor"
      BASIC_AUTH_PASS: "250109"
    ports:
      - "5173:80"
    depends_on:
      - backend

networks:
  invest-net:
